jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]  # Specify the OS platforms for which to build
        arch: [amd64, arm64]  # Specify the architectures (AMD64, ARM64)

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      # Build the binary for each OS/Arch
      - name: Build Binary
        run: |
          VERSION=${{ github.event.inputs.version }}
          OS=${{ matrix.os }}
          ARCH=${{ matrix.arch }}
          REPO_NAME=$(basename $GITHUB_REPOSITORY)  # Get repo name dynamically
          echo "Building $REPO_NAME with version: $VERSION for $OS/$ARCH"
          GOOS=$OS GOARCH=$ARCH go build -o ${REPO_NAME}-${VERSION}-${OS}-${ARCH} -ldflags "-X github.com/EdgeLordKirito/goFTree/internal/goFTree/version.Version=${VERSION}"
